version: '3'
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes: 
      - ./app:./app
    ports:
      - "3000:3000"


  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./app:/app  # Assuming your Python app files are in a folder named 'app'
    networks:
      - minio_network
      - psql_network
    ports:
      - "8000:8000"


  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      - ./db_init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - psql_network
    ports:
      - "5432:5432"
    

  minio:
    image: minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: your_access_key_here
      MINIO_ROOT_PASSWORD: your_secret_key_here
    volumes:
      - minio_vol:/data
    command: server /data
    networks:
      - minio_network

networks:
  minio_network:
    driver: bridge
  psql_network:
    driver: bridge

volumes:
  minio_vol:
