version: '3'
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    env_file:
      - .env
    volumes: 
      - ./app:./app
    ports:
      - 3000:3000


  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - .env
    volumes:
      - ./backend:/backend
    networks:
      - minio_network
      - psql_network
    ports:
      - 8000:8000


  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      - ./db_init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - psql_network
    ports:
      - 5432:5432
    

  minio:
    image: minio/minio:latest
    container_name: minio
    env_file:
      - .env
    volumes:
      - minio_vol:/data
    command: server /minio_vol --console-address ":9001"
    networks:
      - minio_network
    ports:
      - 9000:9000
      - 9001:9001


networks:
  minio_network:
    driver: bridge
  psql_network:
    driver: bridge


volumes:
  minio_vol:
